export const emotes = {
  id: "7387955",
  platform: "KICK",
  username: "drkness-x",
  display_name: "DRKNESS_x",
  linked_at: 1687196320785,
  emote_capacity: 1000,
  emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
  emote_set: {
    id: "01GWJ1AEW0000BBBSQZ83266M8",
    name: "DRKNESS_x Emotes",
    flags: 0,
    tags: [],
    immutable: false,
    privileged: false,
    emotes: [
      {
        id: "01GXZ6XDZG000ENJJARE9FMMPA",
        name: "SoyShaker",
        flags: 0,
        timestamp: 1681453398000,
        actor_id: "01GGGJ9FJR0004VVJPGDR55RYP",
        data: {
          id: "01GXZ6XDZG000ENJJARE9FMMPA",
          name: "SoyShaker",
          flags: 0,
          lifecycle: 3,
          state: ["LISTED"],
          listed: true,
          animated: true,
          owner: {
            id: "01GGGJ9FJR0004VVJPGDR55RYP",
            username: "drkness_x",
            display_name: "DRKNESS_x",
            avatar_url: "//cdn.7tv.app/user/01GGGJ9FJR0004VVJPGDR55RYP/profile-picture/01HXDSSKCG00035YND6GNXR34J/3x.png",
            style: {
              color: -5635841,
              paint_id: "01JHXJFACX42RV996VE9933TB8",
              badge_id: "01GF1YBDFR000DVC9C9H7Q0YHZ",
            },
            role_ids: ["01F37R3RFR0000K96678WEQT01", "01JAMR3H2DDR3Q8D6FZJEM96QS", "01G68MMQFR0007J6GNM9E2M0TM"],
            connections: [
              {
                id: "137521851",
                platform: "TWITCH",
                username: "drkness_x",
                display_name: "DRKNESS_x",
                linked_at: 1667003367282,
                emote_capacity: 1000,
                emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
              },
              {
                id: "7387955",
                platform: "KICK",
                username: "drkness-x",
                display_name: "DRKNESS_x",
                linked_at: 1687196320785,
                emote_capacity: 1000,
                emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
              },
              {
                id: "667619257168691200",
                platform: "DISCORD",
                username: ".itsdark.",
                display_name: "Darkness",
                linked_at: 1736780871043,
                emote_capacity: 1000,
                emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
              },
            ],
          },
          host: {
            url: "//cdn.7tv.app/emote/01GXZ6XDZG000ENJJARE9FMMPA",
            files: [
              {
                name: "1x.webp",
                static_name: "1x_static.webp",
                width: 34,
                height: 32,
                frame_count: 97,
                size: 56156,
                format: "WEBP",
              },
              {
                name: "2x.webp",
                static_name: "2x_static.webp",
                width: 68,
                height: 64,
                frame_count: 97,
                size: 112654,
                format: "WEBP",
              },
              {
                name: "3x.webp",
                static_name: "3x_static.webp",
                width: 102,
                height: 96,
                frame_count: 97,
                size: 166950,
                format: "WEBP",
              },
              {
                name: "4x.webp",
                static_name: "4x_static.webp",
                width: 136,
                height: 128,
                frame_count: 97,
                size: 219844,
                format: "WEBP",
              },
              {
                name: "1x.avif",
                static_name: "1x_static.avif",
                width: 34,
                height: 32,
                frame_count: 97,
                size: 32870,
                format: "AVIF",
              },
              {
                name: "2x.avif",
                static_name: "2x_static.avif",
                width: 68,
                height: 64,
                frame_count: 97,
                size: 75076,
                format: "AVIF",
              },
              {
                name: "3x.avif",
                static_name: "3x_static.avif",
                width: 102,
                height: 96,
                frame_count: 97,
                size: 124632,
                format: "AVIF",
              },
              {
                name: "4x.avif",
                static_name: "4x_static.avif",
                width: 136,
                height: 128,
                frame_count: 97,
                size: 173407,
                format: "AVIF",
              },
              {
                name: "1x.gif",
                static_name: "1x_static.gif",
                width: 34,
                height: 32,
                frame_count: 96,
                size: 42143,
                format: "GIF",
              },
              {
                name: "2x.gif",
                static_name: "2x_static.gif",
                width: 68,
                height: 64,
                frame_count: 97,
                size: 136799,
                format: "GIF",
              },
              {
                name: "3x.gif",
                static_name: "3x_static.gif",
                width: 102,
                height: 96,
                frame_count: 97,
                size: 268135,
                format: "GIF",
              },
              {
                name: "4x.gif",
                static_name: "4x_static.gif",
                width: 136,
                height: 128,
                frame_count: 97,
                size: 430646,
                format: "GIF",
              },
            ],
          },
        },
        origin_id: null,
      },
      {
        id: "01FK4ZFNDR000CCCJ7DMGD0H94",
        name: "SAJ",
        flags: 0,
        timestamp: 1635476035000,
        actor_id: "01GGGJ9FJR0004VVJPGDR55RYP",
        data: {
          id: "01FK4ZFNDR000CCCJ7DMGD0H94",
          name: "SAJ",
          flags: 0,
          tags: ["spunchbob", "spongebob", "sponge", "spongepls", "sadge", "sad"],
          lifecycle: 3,
          state: ["PERSONAL", "LISTED"],
          listed: true,
          animated: false,
          owner: {
            id: "01EZP56B8G0009D0SFZ9W8MQRM",
            username: "hyru",
            display_name: "hyru",
            avatar_url: "//cdn.7tv.app/user/01EZP56B8G0009D0SFZ9W8MQRM/profile-picture/01JF6A02W4VHGWAZNRNB7NEWPW/4x.png",
            style: {
              color: 849892095,
              paint_id: "01GR7C6SD0000CT0EJ9JCPKQS3",
              badge_id: "01GAFARYP0000E8VNG1S1RMTBJ",
            },
            role_ids: ["01F2Z8C8M8000EJFC2HFW8B1W9", "01F37R3RFR0000K96678WEQT01", "01G68MMQFR0007J6GNM9E2M0TM"],
            connections: [
              {
                id: "653124240047865889",
                platform: "DISCORD",
                username: "hyru",
                display_name: "hyru",
                linked_at: 1686381595475,
                emote_capacity: 1000,
                emote_set_id: "01EZP56B8G0009D0SFZ9W8MQRM",
              },
              {
                id: "171892065",
                platform: "TWITCH",
                username: "hyruverse",
                display_name: "hyruverse",
                linked_at: 1614577610000,
                emote_capacity: 1000,
                emote_set_id: "01EZP56B8G0009D0SFZ9W8MQRM",
              },
              {
                id: "UClyRJBkBmo7lEN-js11ZDUg",
                platform: "YOUTUBE",
                username: "",
                display_name: "",
                linked_at: 1614577610000,
                emote_capacity: 1000,
                emote_set_id: "01EZP56B8G0009D0SFZ9W8MQRM",
              },
              {
                id: "68534",
                platform: "KICK",
                username: "hyru",
                display_name: "hyru",
                linked_at: 1688326568015,
                emote_capacity: 1000,
                emote_set_id: "01EZP56B8G0009D0SFZ9W8MQRM",
              },
            ],
          },
          host: {
            url: "//cdn.7tv.app/emote/01FK4ZFNDR000CCCJ7DMGD0H94",
            files: [
              {
                name: "1x.webp",
                static_name: "1x.webp",
                width: 32,
                height: 32,
                frame_count: 1,
                size: 1366,
                format: "WEBP",
              },
              {
                name: "2x.webp",
                static_name: "2x.webp",
                width: 64,
                height: 64,
                frame_count: 1,
                size: 3636,
                format: "WEBP",
              },
              {
                name: "3x.webp",
                static_name: "3x.webp",
                width: 96,
                height: 96,
                frame_count: 1,
                size: 6732,
                format: "WEBP",
              },
              {
                name: "4x.webp",
                static_name: "4x.webp",
                width: 128,
                height: 128,
                frame_count: 1,
                size: 10278,
                format: "WEBP",
              },
              {
                name: "1x.avif",
                static_name: "1x.avif",
                width: 32,
                height: 32,
                frame_count: 1,
                size: 1831,
                format: "AVIF",
              },
              {
                name: "2x.avif",
                static_name: "2x.avif",
                width: 64,
                height: 64,
                frame_count: 1,
                size: 4243,
                format: "AVIF",
              },
              {
                name: "3x.avif",
                static_name: "3x.avif",
                width: 96,
                height: 96,
                frame_count: 1,
                size: 6949,
                format: "AVIF",
              },
              {
                name: "4x.avif",
                static_name: "4x.avif",
                width: 128,
                height: 128,
                frame_count: 1,
                size: 10158,
                format: "AVIF",
              },
              {
                name: "1x.png",
                static_name: "1x.png",
                width: 32,
                height: 32,
                frame_count: 1,
                size: 3095,
                format: "PNG",
              },
              {
                name: "2x.png",
                static_name: "2x.png",
                width: 64,
                height: 64,
                frame_count: 1,
                size: 10783,
                format: "PNG",
              },
              {
                name: "3x.png",
                static_name: "3x.png",
                width: 96,
                height: 96,
                frame_count: 1,
                size: 22206,
                format: "PNG",
              },
              {
                name: "4x.png",
                static_name: "4x.png",
                width: 128,
                height: 128,
                frame_count: 1,
                size: 37892,
                format: "PNG",
              },
            ],
          },
        },
        origin_id: null,
      },
      {
        id: "01GE6ZEN3000010B012TBWZDGK",
        name: "frenn",
        flags: 0,
        timestamp: 1664534140000,
        actor_id: "01GGGJ9FJR0004VVJPGDR55RYP",
        data: {
          id: "01GE6ZEN3000010B012TBWZDGK",
          name: "frenn",
          flags: 0,
          tags: ["halloween", "peepoween", "happ", "sajj", "majj", "pogg"],
          lifecycle: 3,
          state: ["LISTED"],
          listed: true,
          animated: false,
          owner: {
            id: "01FBMXPE200006BMXCG383FV3Q",
            username: "soaral",
            display_name: "Soaral",
            avatar_url:
              "https://static-cdn.jtvnw.net/jtv_user_pictures/38c0ef09-4fd0-4a1c-aa6d-c7bb6a68af74-profile_image-300x300.png",
            style: {
              badge_id: "01JF2VMDBWMZDXZKF4D33VM2S8",
            },
            role_ids: ["01G68MMQFR0007J6GNM9E2M0TM"],
            connections: [
              {
                id: "535588710",
                platform: "TWITCH",
                username: "soaral",
                display_name: "Soaral",
                linked_at: 1662989487812,
                emote_capacity: 1000,
                emote_set_id: "01GCRWZ8XR000AMQSD9V5W24BY",
              },
              {
                id: "UCtG-xhDJnXBIWduyGDlUw3w",
                platform: "YOUTUBE",
                username: "Soaral",
                display_name: "Soaral",
                linked_at: 1661362833114,
                emote_capacity: 1000,
                emote_set_id: "01GCRWZ8XR000AMQSD9V5W24BY",
              },
            ],
          },
          host: {
            url: "//cdn.7tv.app/emote/01GE6ZEN3000010B012TBWZDGK",
            files: [
              {
                name: "1x.webp",
                static_name: "1x.webp",
                width: 53,
                height: 32,
                frame_count: 1,
                size: 2280,
                format: "WEBP",
              },
              {
                name: "2x.webp",
                static_name: "2x.webp",
                width: 106,
                height: 64,
                frame_count: 1,
                size: 5182,
                format: "WEBP",
              },
              {
                name: "3x.webp",
                static_name: "3x.webp",
                width: 159,
                height: 96,
                frame_count: 1,
                size: 8620,
                format: "WEBP",
              },
              {
                name: "4x.webp",
                static_name: "4x.webp",
                width: 212,
                height: 128,
                frame_count: 1,
                size: 12462,
                format: "WEBP",
              },
              {
                name: "1x.avif",
                static_name: "1x.avif",
                width: 53,
                height: 32,
                frame_count: 1,
                size: 1759,
                format: "AVIF",
              },
              {
                name: "2x.avif",
                static_name: "2x.avif",
                width: 106,
                height: 64,
                frame_count: 1,
                size: 3293,
                format: "AVIF",
              },
              {
                name: "3x.avif",
                static_name: "3x.avif",
                width: 159,
                height: 96,
                frame_count: 1,
                size: 4801,
                format: "AVIF",
              },
              {
                name: "4x.avif",
                static_name: "4x.avif",
                width: 212,
                height: 128,
                frame_count: 1,
                size: 6313,
                format: "AVIF",
              },
              {
                name: "1x.png",
                static_name: "1x.png",
                width: 53,
                height: 32,
                frame_count: 1,
                size: 2610,
                format: "PNG",
              },
              {
                name: "2x.png",
                static_name: "2x.png",
                width: 106,
                height: 64,
                frame_count: 1,
                size: 6438,
                format: "PNG",
              },
              {
                name: "3x.png",
                static_name: "3x.png",
                width: 159,
                height: 96,
                frame_count: 1,
                size: 10974,
                format: "PNG",
              },
              {
                name: "4x.png",
                static_name: "4x.png",
                width: 212,
                height: 128,
                frame_count: 1,
                size: 16340,
                format: "PNG",
              },
            ],
          },
        },
        origin_id: null,
      },
      {
        id: "01GG3YGWK8000DWE419062SG28",
        name: "Stare",
        flags: 0,
        timestamp: 1666579985000,
        actor_id: "01F6MBDQ7R0005TFYTWP1R54KA",
        data: {
          id: "01GG3YGWK8000DWE419062SG28",
          name: "Stare",
          flags: 0,
          lifecycle: 3,
          state: ["LISTED"],
          listed: true,
          animated: false,
          owner: {
            id: "01F6Q2PKA00009K4HVQSZPWPHK",
            username: "trippycolour",
            display_name: "TrippyColour",
            avatar_url: "//cdn.7tv.app/user/01F6Q2PKA00009K4HVQSZPWPHK/profile-picture/01J01V0XWR0001WWQ8ZKWKQZY8/3x.avif",
            style: {
              color: -5635841,
              paint_id: "01JEY00EDNVW20AWX2NPG4HTNF",
            },
            role_ids: ["01F37R3RFR0000K96678WEQT01", "01G68MMQFR0007J6GNM9E2M0TM"],
            connections: [
              {
                id: "121081148",
                platform: "TWITCH",
                username: "trippycolour",
                display_name: "TrippyColour",
                linked_at: 1622124744000,
                emote_capacity: 1000,
                emote_set_id: "01F6Q2PKA00009K4HVQSZPWPHK",
              },
              {
                id: "189126788872404992",
                platform: "DISCORD",
                username: "Trippy",
                display_name: "Trippy",
                linked_at: 1658606902057,
                emote_capacity: 1000,
                emote_set_id: "01F6Q2PKA00009K4HVQSZPWPHK",
              },
            ],
          },
          host: {
            url: "//cdn.7tv.app/emote/01GG3YGWK8000DWE419062SG28",
            files: [
              {
                name: "1x.webp",
                static_name: "1x.webp",
                width: 37,
                height: 32,
                frame_count: 1,
                size: 1758,
                format: "WEBP",
              },
              {
                name: "2x.webp",
                static_name: "2x.webp",
                width: 74,
                height: 64,
                frame_count: 1,
                size: 4110,
                format: "WEBP",
              },
              {
                name: "3x.webp",
                static_name: "3x.webp",
                width: 111,
                height: 96,
                frame_count: 1,
                size: 6786,
                format: "WEBP",
              },
              {
                name: "4x.webp",
                static_name: "4x.webp",
                width: 148,
                height: 128,
                frame_count: 1,
                size: 9802,
                format: "WEBP",
              },
              {
                name: "1x.avif",
                static_name: "1x.avif",
                width: 37,
                height: 32,
                frame_count: 1,
                size: 1567,
                format: "AVIF",
              },
              {
                name: "2x.avif",
                static_name: "2x.avif",
                width: 74,
                height: 64,
                frame_count: 1,
                size: 3068,
                format: "AVIF",
              },
              {
                name: "3x.avif",
                static_name: "3x.avif",
                width: 111,
                height: 96,
                frame_count: 1,
                size: 4581,
                format: "AVIF",
              },
              {
                name: "4x.avif",
                static_name: "4x.avif",
                width: 148,
                height: 128,
                frame_count: 1,
                size: 6178,
                format: "AVIF",
              },
              {
                name: "1x.png",
                static_name: "1x.png",
                width: 37,
                height: 32,
                frame_count: 1,
                size: 2025,
                format: "PNG",
              },
              {
                name: "2x.png",
                static_name: "2x.png",
                width: 74,
                height: 64,
                frame_count: 1,
                size: 4880,
                format: "PNG",
              },
              {
                name: "3x.png",
                static_name: "3x.png",
                width: 111,
                height: 96,
                frame_count: 1,
                size: 8250,
                format: "PNG",
              },
              {
                name: "4x.png",
                static_name: "4x.png",
                width: 148,
                height: 128,
                frame_count: 1,
                size: 12337,
                format: "PNG",
              },
            ],
          },
        },
        origin_id: null,
      },
    ],
    emote_count: 17,
    capacity: 1000,
    owner: null,
  },
  user: {
    id: "01GGGJ9FJR0004VVJPGDR55RYP",
    username: "drkness_x",
    display_name: "DRKNESS_x",
    created_at: 1667003367000,
    avatar_url: "//cdn.7tv.app/user/01GGGJ9FJR0004VVJPGDR55RYP/profile-picture/01HXDSSKCG00035YND6GNXR34J/3x.png",
    style: {
      color: -5635841,
      paint_id: "01JHXJFACX42RV996VE9933TB8",
      badge_id: "01GF1YBDFR000DVC9C9H7Q0YHZ",
    },
    emote_sets: [
      {
        id: "01GWJ18EDG000ETW2ZY26GXQ2R",
        name: "Personal Emotes",
        flags: 4,
        tags: [],
        capacity: 5,
      },
      {
        id: "01GWJ1AEW0000BBBSQZ83266M8",
        name: "DRKNESS_x Emotes",
        flags: 0,
        tags: [],
        capacity: 1000,
      },
      {
        id: "01HBKGKKDG000D2TB3512PSH9A",
        name: "sd",
        flags: 0,
        tags: [],
        capacity: 1000,
      },
    ],
    roles: ["01G68MMQFR0007J6GNM9E2M0TM", "01JAMR3H2DDR3Q8D6FZJEM96QS", "01F37R3RFR0000K96678WEQT01"],
    connections: [
      {
        id: "137521851",
        platform: "TWITCH",
        username: "drkness_x",
        display_name: "DRKNESS_x",
        linked_at: 1667003367282,
        emote_capacity: 1000,
        emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
        emote_set: null,
      },
      {
        id: "7387955",
        platform: "KICK",
        username: "drkness-x",
        display_name: "DRKNESS_x",
        linked_at: 1687196320785,
        emote_capacity: 1000,
        emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
        emote_set: null,
      },
      {
        id: "667619257168691200",
        platform: "DISCORD",
        username: ".itsdark.",
        display_name: "Darkness",
        linked_at: 1736780871043,
        emote_capacity: 1000,
        emote_set_id: "01GWJ1AEW0000BBBSQZ83266M8",
        emote_set: null,
      },
    ],
  },
};
